DealRept/Controllers/BanksController.cs
using ClosedXML.Excel;
using DealRept.Models;
using DealRept.Models.ViewModel;
using DealRept.Utilities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace DealRept.Controllers
{
    [Authorize(Roles = "ContractStaff, BranchStaff, Administrator")]
    public class BanksController : Controller
    {
        private const string PatternName = @"^[a-zA-Z][a-zA-Z\s-,]+[a-zA-Z]$";
        private const string PatternCode = @"[0-9]{6}";
        private readonly DealDbContext _context;
        private readonly ILogger<BanksController> _logger;
        private readonly IConfiguration _configuration;

        public BanksController(DealDbContext ctx, ILogger<BanksController> logger,
            IConfiguration configuration)
        {
            _context = ctx;
            _logger = logger;
            _configuration = configuration;
        }

        public async Task<IActionResult> Index(int? pageNumber, SortModel sortModel, string sortOrder, SearchModel searchModel,
           string currentFilterNameCode, string currentFilterLastAdded)
        {
            sortModel.CurrentSort = sortOrder;
            sortModel.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "Name_desc" : "";

            if (searchModel.NameCodeBankSearch != null || searchModel.LastAdded != default)
            {
                pageNumber = 1;
            }
            else
            {
                searchModel.LastAdded = (currentFilterLastAdded != default) ? Int32.Parse(currentFilterLastAdded) : default;
                searchModel.NameCodeBankSearch = currentFilterNameCode;
            }

            IQueryable<Bank> banks = _context.Banks.AsNoTracking()
                .Select(b => new Bank
                {
                    Name = b.Name,
                    Code = b.Code,
                    ID = b.ID,
                    SuppliersCount = (from s in _context.Suppliers where s.BankID == b.ID select s.ID).Count()
                });

            if (searchModel != null)
            {
                if (searchModel.NameCodeBankSearch != null)
                {
                    banks = banks.Where(b => b.Name.Contains(searchModel.NameCodeBankSearch)
                    || b.Code.Contains(searchModel.NameCodeBankSearch));
                }
                if (searchModel.LastAdded != default)
                {
                    banks = banks.OrderByDescending(b => b.ID).Take(searchModel.LastAdded);
                }
            }

            switch (sortOrder)
            {
                case "Name_desc":
                    banks = banks.OrderByDescending(b => b.Name); break;
                default:
                    banks = banks.OrderBy(b => b.Name); break;
            }

            int pageSize = 10;

            return View(await PaginatedList<Bank>.CreateAsync(banks.AsNoTracking(), pageNumber ?? 1, pageSize, searchModel, sortModel));
        }

        [Authorize(Roles = "ContractStaff")]
        public IActionResult Create()
        {
            return View(new Bank());
        }

        [Authorize(Roles = "ContractStaff")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Name", "Code")] Bank bankToCreate)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Banks.Add(bankToCreate);
                    await _context.SaveChangesAsync();

                    Bank newBank = await _context.Banks.FirstOrDefaultAsync(b => b.Code == bankToCreate.Code);

                    if (newBank == null)
                    {
                        throw new ElementNotFoundException("Something went wrong during Bank creation,"
                            , new ArgumentNullException($"{nameof(newBank)}"));
                    }

                    return RedirectToAction(nameof(Index), new { currentFilterNameCode = newBank.Code });
                }
            }
            catch (DbUpdateException dBUpEx)
            {
                _logger.LogError(dBUpEx, "Unable to save changes to DB");
                ModelState.AddModelError("", "Unable to save changes. " +
                                "Try again, and if the problem persists " +
                                "see your system administrator.");
            }

            return View(bankToCreate);
        }

        [Authorize(Roles = "ContractStaff")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                throw new ElementNotFoundException("Something went wrong during Bank edit,",
                    new ArgumentNullException($"{nameof(id)}"));
            }

            Bank bankToEdit = await _context.Banks.FirstOrDefaultAsync(b => b.ID == id);

            if (bankToEdit == null)
            {
                throw new ElementNotFoundException("Something went wrong during Bank edit,",
                                        new ArgumentNullException($"{nameof(bankToEdit)}"));
            }

            return View(bankToEdit);
        }

        [Authorize(Roles = "ContractStaff")]
        [ValidateAntiForgeryToken]
        [HttpPost, ActionName("Edit")]
        public async Task<IActionResult> EditPost(int? id)
        {
            if (id == null)
            {
                throw new ElementNotFoundException("Something went wrong during a Bank edit,",
                    new ArgumentNullException($"{nameof(id)}"));
            }

            Bank bankToUpdate = await _context.Banks.FirstOrDefaultAsync(b => b.ID == id);

            if (bankToUpdate == null)
            {
                throw new ElementNotFoundException("Something went wrong during a Bank edit,",
                                            new ArgumentNullException($"{nameof(bankToUpdate)}"));
            }

            if (await TryUpdateModelAsync<Bank>(bankToUpdate, "", b => b.Name))
            {
                try
                {
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), new { currentFilterNameCode = bankToUpdate.Code });
                }
                catch (DbUpdateException dbUpEx)
                {
                    _logger.LogError(dbUpEx, "Unable to save changes to DB.");
                    ModelState.AddModelError("", "Unable to save changes. " +
                            "Try again, and if the problem persists " +
                            "see your system administrator.");
                }
            }

            return View(bankToUpdate);
        }

        [Authorize(Roles = "ContractStaff")]
        [HttpPost]
        public async Task<bool> Delete(int? id)
        {
            if (id == null)
            {
                _logger.LogError(new ArgumentNullException(nameof(id)), "Delete failed");
                return false;
            }

            Bank bankToDelete = await _context.Banks.FirstOrDefaultAsync(b => b.ID == id);
            if (bankToDelete == null)
            {
                _logger.LogError(new ArgumentNullException(nameof(bankToDelete)), "BankToDelete was not found");
                return true;
            }
            try
            {
                _context.Banks.Remove(bankToDelete);
                await _context.SaveChangesAsync();
                return true;
            }
            catch (DbUpdateException dBUpEx)
            {
                _logger.LogError(dBUpEx, "Delete failed");
                return false;
            }
        }

        [Authorize(Roles = "ContractStaff")]
        public IActionResult ImportData()
        {
            ImportFileViewModel fileVM = new ImportFileViewModel();
            return View(fileVM);
        }

        [Authorize(Roles = "ContractStaff")]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> ImportData(ImportFileViewModel importFileVM)
        {
            if (importFileVM == null)
            {
                throw new ElementNotFoundException("Something went wrong during City import data,",
                    new ArgumentNullException($"{nameof(importFileVM)}"));
            }

            long _fileSizeLimit = _configuration.GetSection("ImportData").GetValue<long>("ImportFileSizeLimit");
            string[] _permittedExtensions = { ".xlsx" };

            if (!ModelState.IsValid)
            {
                return View(importFileVM);
            }

            await FileHelpers.ProcessFormFile<FileUpload>(
                importFileVM.FileToUpload.FormFile, ModelState, _permittedExtensions,
                _fileSizeLimit, _logger);

            if (!ModelState.IsValid)
            {
                return View(importFileVM);
            }

            List<BankViewModel> banks = new List<BankViewModel>();
            const int colBankCode = 3;
            const int colBankName = 4;
            int batchLimit = _configuration.GetSection("ImportData").GetValue<int>("BatchLimit");

            try
            {
                using Stream stream = importFileVM.FileToUpload.FormFile.OpenReadStream();
                using XLWorkbook workBook = new XLWorkbook(stream);
                IXLWorksheet workSheet = workBook.Worksheet(1);

                if (workSheet.LastRowUsed().RowNumber() > (batchLimit + 2)
                || workSheet.FirstRowUsed().CellsUsed().Count() > 3
                || workSheet.FirstRowUsed().Cell(colBankName).GetString() != "Bank Name"
                || workSheet.FirstRowUsed().Cell(colBankCode).GetString() != "Bank Code"
                 || workSheet.FirstRowUsed().RowBelow().Cell(colBankName).IsEmpty())
                {

DealRept/Views/Shared/_Layout.cshtml
@inject SignInManager<User> SignInManager
@inject UserManager<User> UserManager

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script defer src="/js/friconix.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="~/css/cite.css" />

    <link href='https://cdn.jsdelivr.net/npm/@@fortawesome/fontawesome-free@@5.13.1/css/all.css' rel='stylesheet'/>

    <link rel="shortcut icon" href="/images/logoFin.ico"
          type="image/x-icon" />



    <title>@ViewBag.Title</title>
</head>
<body>
    <nav class="navbarPrimary navbar navbar-expand-lg navbar-light bg-white p-0 pl-2">
        <div class="container">
            <div class="align-self-center">
                <a asp-controller="Home" asp-action="Index" class="scaleNavbarBrand navbar-brand px-1 mr-0 mt-3 mt-md-2">
                    <img alt="Deal#Rept" class="img-fluid rounded float-right" src="/images/brand.svg" />
                </a>
            </div>
            <button id="barToggler" class="navbar-toggler text-primary" data-toggle="collapse" data-target="#navbarCollapse">
                <i class="fi-xnlux2-three-bars"></i>
            </button>
            <div class="collapse navbar-collapse mt-md-1" id="navbarCollapse">
                <ul class="navbar-nav">
                    <li class="nav-item px-2">
                        <a asp-controller="Home" asp-action="Index" is-active-route
                           class="nav-link text-primary">Home</a>
                    </li>
                    <li class="nav-item px-2">
                        <a asp-controller="Contracts" asp-action="Index" is-active-route
                           class="nav-link text-primary">Contracts</a>
                    </li>
                    <li class="nav-item px-2">
                        <a asp-controller="Suppliers" asp-action="Index" is-active-route class="nav-link text-primary">Suppliers</a>
                    </li>
                    <li class="nav-item px-2">
                        <a asp-controller="Branches" asp-action="Index" is-active-route class="nav-link text-primary">Branches</a>
                    </li>
                    <li class="nav-item dropdown px-2">
                        <a is-active-route class="nav-link text-primary dropdown-toggle auxiliaries"
                           href="#" role="button" data-toggle="dropdown" aria-expanded="false">Auxiliaries</a>
                        <div class="dropdown-menu p-md-1 dropDownLink">
                            <a is-active-route class="text-primary dropdown-item mb-md-1" asp-controller="Cities" asp-action="Index">Cities</a>
                            <a is-active-route class="text-primary dropdown-item" asp-controller="Banks" asp-action="Index">Banks</a>
                        </div>
                    </li>
                    @if (SignInManager.IsSignedIn(User) && User.IsInRole("Administrator"))
                    {
                        <li class="nav-item px-2">
                            <a asp-controller="Users" asp-action="Index" is-active-route class="nav-link text-primary">Users</a>
                        </li>
                    }
                </ul>
                @{await Html.RenderPartialAsync("_LoginPartial");}
            </div>
        </div>
    </nav>

    <!--HEADER-->

    <header id="main-header" class="bg-white ">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <h1 class="text-primary display-4">
                        @RenderSection("Header", false)
                    </h1>
                </div>
            </div>
        </div>
    </header>
    <div>
        @RenderBody()
    </div>
    <div class="margin_for_footer">
        <footer id="main-footer" class="bg-white footer text-primary">
            <div class="container">
                <div class="row">
                    <div class="col text-center">
                        Copyright &copy;
                        <span id="year"></span>
                        <span class="text-primary">Deal</span><span class="text-success">#</span><span class="text-warning">Rept</span>
                    </div>
                </div>
            </div>
        </footer>
    </div>
    @RenderSection("Scripts", required: false)

    <script src="http://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.5/jquery.validate.js" integrity="sha512-IFD8s8Ds5M/7XsAQXNXtHVdiA8EnBR6bZhy0R+Y7fruej9fNPkrZ6+0/dP8yfRU1u2x9De4WYGCNvoaIhmhnpg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/4.0.0/jquery.validate.unobtrusive.min.js" integrity="sha512-xq+Vm8jC94ynOikewaQXMEkJIOBp7iArs3IhFWSWdRT3Pq8wFz46p+ZDFAR7kHnSFf+zUv52B3prRYnbDRdgog==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/fullcalendar/index.global.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@@fullcalendar/bootstrap@@6.1.10/index.global.min.js" integrity="sha256-ad49/MPAELPf/HGzKuBuRJ/F53St9/sYcD/c5q/Vsoo=" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


    <script src="~/js/cite.js"></script>

    <environment include="Development">
        <script type="text/javascript">
            $.validator.methods.number = function (value, element) {
                return this.optional(element) || /^-?(?:\d+|\d{1,3}(?:\.\d{3})+)?(?:,\d+)?$/.test(value);
            }
        </script>
    </environment>
</body>
</html>

DealRept/Views/Shared/_ModalDeleteEntity.cshtml
       
 <div class="modal fade" id="modalDeleteEntity" tabindex="-1" aria-labelledby="modalDeleteEntityLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title text-warning font-weight-normal lead" id="modalDeleteEntityLabel">Delete a <span id="modalEntity"></span></h5>
                </div>
                <div id="modalMessage" class="modal-body">
                    
                </div>
                <div class="modal-footer justify-content-center align-content-center">
                            <button id="cancelButton" type="button" class="btn btn-link font-weight-light px-4 text-white text-uppercase btn-modal-success mr-4" data-dismiss="modal">Cancel</button>
                            <button id="deleteButton" type="button" class="btn btn-link font-weight-light px-4 text-white text-uppercase btn-modal-warning ml-4">Delete</button>
                </div>
            </div>
        </div>
    </div>

DealRept/Views/Shared/_ModalDirtyChecklPartial.cshtml
@model ModelForDirtyCheckModal

<div class="modal fade" id="@Model.ID" tabindex="-1" aria-labelledby="dirtyCheckModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-warning font-weight-normal lead" id="dirtyCheckModalLabel">Save changes!</h5>
                <button type="button" class="close scaleIcon focusWarning" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="text-warning">&times;</span>
                </button>
            </div>
            <div class="modal-body text-primary">
                You`ve made changes to the @Model.Entity. Not to lose them, you must first save changes!
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button"
                class="btn btn-link font-weight-light px-4 text-white text-uppercase btn-modal-success mr-4"
                        data-dismiss="modal">Save</button>
                <a asp-controller="@Model.Controller" asp-action="@Model.Action" asp-route-id="@Model.RouteData"
                   class="btn btn-link font-weight-light px-3 text-white text-uppercase btn-modal-warning ml-4">Discard</a>
            </div>
        </div>
    </div>
</div>